name: DotnetSixProjectBuilder
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true  
        
     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GGroupp NuGet Source
      run: dotnet nuget add source ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -n ggroupp -u ${{ secrets.GGROUPP_NUGET_SOURCE_USER_NAME }} -p ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --store-password-in-clear-text

    # NumberInWords.fsproj
    
    - name: Restore NumberInWords.fsproj
      run: dotnet restore ./src/*/NumberInWords.fsproj

    - name: Build NumberInWords.fsproj
      run: dotnet build ./src/*/NumberInWords.fsproj --no-restore  -c Release

    - name: Pack NumberInWords.fsproj
      run: dotnet pack ./src/*/NumberInWords.fsproj --no-restore -o ~/nuget  -c Release

    # NumberInWords.Tests.fsproj
    
    - name: Restore NumberInWords.Tests.fsproj
      run: dotnet restore ./src/*/NumberInWords.Tests.fsproj

    - name: Test NumberInWords.Tests.fsproj
      run: dotnet test ./src/*/NumberInWords.Tests.fsproj --no-restore  -c Release